In [1]:
import pandas as pd
import numpy as np

df=pd.read_csv("/content/cleaned_global_ecommerce_data.csv")

,Transaction_ID,Date,Customer_ID,Customer_Age,Gender,Location,Product_Category,Product_Name,Unit_Price,Quantity,Discount_Applied,Total_Revenue,Payment_Method,Delivery_Time_Days,Customer_Rating
0,TXN1000,2023-01-01,CUST_4764,39,Male,Pakistan,Apparel,Cotton T-Shirt,89.50,3,0.04,257.76,PayPal,8,3.3
1,TXN1001,2023-01-01,CUST_20831,33,Male,Germany,Electronics,4K Smart TV,1129.50,3,0.05,3219.07,Credit Card,9,3.8
2,TXN1002,2023-01-01,CUST_15374,41,Non-binary,Germany,Home & Kitchen,Air Fryer,195.79,2,0.13,340.67,Credit Card,14,1.5
3,TXN1003,2023-01-01,CUST_17541,50,Non-binary,UAE,Electronics,Gaming Laptop,1153.43,1,0.10,1038.09,Bank Transfer,11,1.6
4,TXN1004,2023-01-01,CUST_14124,32,Male,UAE,Apparel,Formal Shirt,146.54,2,0.08,269.63,Credit Card,6,4.5

In [2]:
df

,Transaction_ID,Date,Customer_ID,Customer_Age,Gender,Location,Product_Category,Product_Name,Unit_Price,Quantity,Discount_Applied,Total_Revenue,Payment_Method,Delivery_Time_Days,Customer_Rating
0,TXN1000,2023-01-01,CUST_4764,39,Male,Pakistan,Apparel,Cotton T-Shirt,89.50,3,0.04,257.76,PayPal,8,3.3
1,TXN1001,2023-01-01,CUST_20831,33,Male,Germany,Electronics,4K Smart TV,1129.50,3,0.05,3219.07,Credit Card,9,3.8
2,TXN1002,2023-01-01,CUST_15374,41,Non-binary,Germany,Home & Kitchen,Air Fryer,195.79,2,0.13,340.67,Credit Card,14,1.5
3,TXN1003,2023-01-01,CUST_17541,50,Non-binary,UAE,Electronics,Gaming Laptop,1153.43,1,0.10,1038.09,Bank Transfer,11,1.6
4,TXN1004,2023-01-01,CUST_14124,32,Male,UAE,Apparel,Formal Shirt,146.54,2,0.08,269.63,Credit Card,6,4.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,TXN50995,2026-06-01,CUST_20242,35,Female,Pakistan,Electronics,4K Smart TV,1100.15,2,0.13,1914.26,Credit Card,13,2.2
49996,TXN50996,2026-06-01,CUST_16159,34,Male,UK,Electronics,4K Smart TV,134.01,3,0.08,369.87,Credit Card,2,4.4
49997,TXN50997,2026-06-01,CUST_22746,40,Female,UK,Electronics,4K Smart TV,473.73,1,0.12,416.88,Bank Transfer,1,5.0
49998,TXN50998,2026-06-01,CUST_11975,37,Non-binary,Germany,Sports,Football,168.56,1,0.05,160.13,Crypto,10,3.0
49999,TXN50999,2026-06-01,CUST_5452,50,Male,Pakistan,Home & Kitchen,Air Fryer,254.14,3,0.11,678.55,Bank Transfer,2,3.8

In [3]:
df.isnull().sum()

Transaction_ID        0
Date                  0
Customer_ID           0
Customer_Age          0
Gender                0
Location              0
Product_Category      0
Product_Name          0
Unit_Price            0
Quantity              0
Discount_Applied      0
Total_Revenue         0
Payment_Method        0
Delivery_Time_Days    0
Customer_Rating       0
dtype: int64

In [4]:
duplicates = df[df.duplicated(keep=False)]

print(duplicates)

Empty DataFrame
Columns: [Transaction_ID, Date, Customer_ID, Customer_Age, Gender, Location, Product_Category, Product_Name, Unit_Price, Quantity, Discount_Applied, Total_Revenue, Payment_Method, Delivery_Time_Days, Customer_Rating]
Index: []

In [5]:
import pandas as pd

bins = [0, 18, 25, 35, 45, 60, 100]
labels = ['Under 18', '18-24', '25-34', '35-44', '45-59', '60+']

df['Age_Group'] = pd.cut(
    df['Customer_Age'],
    bins=bins,
    labels=labels,
    right=False
)

# Count customers in each age group
df['Age_Group'].value_counts().sort_index()

Age_Group
Under 18        0
18-24        7920
25-34       17048
35-44       17091
45-59        7639
60+           302
Name: count, dtype: int64

In [6]:
df.Payment_Method.unique()

array(['PayPal', 'Credit Card', 'Bank Transfer', 'Crypto'], dtype=object)

In [7]:
df

,Transaction_ID,Date,Customer_ID,Customer_Age,Gender,Location,Product_Category,Product_Name,Unit_Price,Quantity,Discount_Applied,Total_Revenue,Payment_Method,Delivery_Time_Days,Customer_Rating,Age_Group
0,TXN1000,2023-01-01,CUST_4764,39,Male,Pakistan,Apparel,Cotton T-Shirt,89.50,3,0.04,257.76,PayPal,8,3.3,35-44
1,TXN1001,2023-01-01,CUST_20831,33,Male,Germany,Electronics,4K Smart TV,1129.50,3,0.05,3219.07,Credit Card,9,3.8,25-34
2,TXN1002,2023-01-01,CUST_15374,41,Non-binary,Germany,Home & Kitchen,Air Fryer,195.79,2,0.13,340.67,Credit Card,14,1.5,35-44
3,TXN1003,2023-01-01,CUST_17541,50,Non-binary,UAE,Electronics,Gaming Laptop,1153.43,1,0.10,1038.09,Bank Transfer,11,1.6,45-59
4,TXN1004,2023-01-01,CUST_14124,32,Male,UAE,Apparel,Formal Shirt,146.54,2,0.08,269.63,Credit Card,6,4.5,25-34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,TXN50995,2026-06-01,CUST_20242,35,Female,Pakistan,Electronics,4K Smart TV,1100.15,2,0.13,1914.26,Credit Card,13,2.2,35-44
49996,TXN50996,2026-06-01,CUST_16159,34,Male,UK,Electronics,4K Smart TV,134.01,3,0.08,369.87,Credit Card,2,4.4,25-34
49997,TXN50997,2026-06-01,CUST_22746,40,Female,UK,Electronics,4K Smart TV,473.73,1,0.12,416.88,Bank Transfer,1,5.0,35-44
49998,TXN50998,2026-06-01,CUST_11975,37,Non-binary,Germany,Sports,Football,168.56,1,0.05,160.13,Crypto,10,3.0,35-44
49999,TXN50999,2026-06-01,CUST_5452,50,Male,Pakistan,Home & Kitchen,Air Fryer,254.14,3,0.11,678.55,Bank Transfer,2,3.8,45-59

In [9]:

df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

In [10]:
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Month_Name'] = df['Date'].dt.month_name()
df['Day'] = df['Date'].dt.day
df['Day_Name'] = df['Date'].dt.day_name()
df.head()

,Transaction_ID,Date,Customer_ID,Customer_Age,Gender,Location,Product_Category,Product_Name,Unit_Price,Quantity,...,Total_Revenue,Payment_Method,Delivery_Time_Days,Customer_Rating,Age_Group,Year,Month,Month_Name,Day,Day_Name
0,TXN1000,2023-01-01,CUST_4764,39,Male,Pakistan,Apparel,Cotton T-Shirt,89.50,3,...,257.76,PayPal,8,3.3,35-44,2023,1,January,1,Sunday
1,TXN1001,2023-01-01,CUST_20831,33,Male,Germany,Electronics,4K Smart TV,1129.50,3,...,3219.07,Credit Card,9,3.8,25-34,2023,1,January,1,Sunday
2,TXN1002,2023-01-01,CUST_15374,41,Non-binary,Germany,Home & Kitchen,Air Fryer,195.79,2,...,340.67,Credit Card,14,1.5,35-44,2023,1,January,1,Sunday
3,TXN1003,2023-01-01,CUST_17541,50,Non-binary,UAE,Electronics,Gaming Laptop,1153.43,1,...,1038.09,Bank Transfer,11,1.6,45-59,2023,1,January,1,Sunday
4,TXN1004,2023-01-01,CUST_14124,32,Male,UAE,Apparel,Formal Shirt,146.54,2,...,269.63,Credit Card,6,4.5,25-34,2023,1,January,1,Sunday

In [13]:
df.columns

Index(['Transaction_ID', 'Date', 'Customer_ID', 'Customer_Age', 'Gender',
       'Location', 'Product_Category', 'Product_Name', 'Unit_Price',
       'Quantity', 'Discount_Applied', 'Total_Revenue', 'Payment_Method',
       'Delivery_Time_Days', 'Customer_Rating', 'Age_Group', 'Year', 'Month',
       'Month_Name', 'Day', 'Day_Name'],
      dtype='object')

In [16]:
df=df.drop(['Customer_Age'],axis=1)